import userRoutes from "../routes/userRoutes.js";
import urgentMessageRouter from "../routes/urgentMessageRoute.js";
import express from "express";
import voltRouter from "../routes/voltRoutes.js";
import eventRouter from "../routes/eventRoutes.js";
const router = express.Router();
router.use('/users', userRoutes);
router.use('/urgent', urgentMessageRouter);
router.use('/volt', voltRouter);
router.use('/event', eventRouter);
export default router;